---
title: TestCacheInvalidation 中に Web 層パイプラインの実行が失敗する
description: 説明
solution: Experience Manager as a Cloud Service
product: Experience Manager as a Cloud Service
applies-to: Experience Manager as a Cloud Service
keywords: KCS
resolution: Resolution
internal-notes: answer found in https://dmasupport.slack.com/archives/C013SBSHPKK/p1645102872540889?thread_ts=1645102277.855389&cid=C013SBSHPKK
bug: false
article-created-by: Vincent Frey
article-created-date: 3/31/2022 6:42:09 AM
article-published-by: Vincent Frey
article-published-date: 3/31/2022 6:52:55 AM
version-number: 1
article-number: KA-19052
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=4a8a30af-bdb0-ec11-9840-0022480bde18
exl-id: 29d6e807-7757-443e-9fdf-57af339f00d7
source-git-commit: 6a23faae10364181be7dedc2f408f2ad8d8be3c9
workflow-type: tm+mt
source-wordcount: '114'
ht-degree: 3%

---

# TestCacheInvalidation 中に Web 層パイプラインの実行が失敗する

## 説明


Web 層パイプラインの実行が失敗し、ログに次のメッセージが表示されます。

```
=== RUN TestCacheInvalidation
main_test.go:237: Test fails. Expected header 'X-Vhost' to be existing and not: 'catch-all', got: 'catch-all'
--- FAIL: TestCacheInvalidation (0.00s)
FAIL
exit status 1<br><br>
```


## 解決策


次の項目を確認します。 [!DNL Dispatcher] 設定で、次のように一部の vhost が正しく設定されています。 [!DNL Dispatcher] キャッシュの無効化（ホスト 127.0.0.1 への呼び出し）と、空でない X-Vhost ヘッダーセットがある場合

例： https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/dispatcher.cloud/src/conf.d/available_vhosts/default.vhost#L24

https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/dispatcher.cloud/src/conf.d/dispatcher_vhost.conf#L136のように、X-Vhost ヘッダーが「catch-all」に設定されている catch-all vhost にリクエストが到達しないことを示しています。
